elixir-tesla/tesla

- lib/tesla.ex
- lib/tesla/middleware/core.ex
Hi,
Thanks for building this nice looking library!
While I was reading the source code, I found a few things could be made "better".
Let me know if there is anything you want to keep as is, e.g. explicit call to generate very http verb
Thanks again
Po
> Minor cleanups

- README.md
As someone new to Phoenix it was something that stumped me for a little while. Hopefully this makes it quicker for the next person. 😄
> Add information about having to add the adapter dependancy.

- README.md
* Use double-quotes over single quotes
* Modify token format
> Update Github example

- README.md
Hello!
This small PR updates the README to describe a small change required for the dynamic middleware examples to work.
Cheers.
> Small fix to the dynamic middleware example

- README.md
- lib/tesla/middleware/form_urlencoded.ex
- mix.lock
- test/tesla/middleware/form_urlencoded_test.exs
A middleware for urlencoding POST data parameter, useful for providing POST data as a map or keyword list
> Add Tesla.Middleware.FormUrlencoded

- lib/tesla/middleware/compression.ex
- test/tesla/middleware/compression_test.exs
I'm not expert on content-encoding, but it covers my needs in another project, so I decided to make PR
> middleware for data compression

- lib/tesla/middleware/json.ex
- test/tesla/middleware/json_test.exs
* Solution proposal for #50 
* CustomClient with engine opts wasn't used in any test, fixed
> Improved json middleware

- README.md
> Most critical contribution of all time (fix typo)

- lib/tesla/adapter/httpc.ex
- lib/tesla/adapter/ibrowse.ex
- lib/tesla/adapter/shared.ex
- test/tesla/adapter/ibrowse_test.exs
Stream support for httpc and ibrowse seems to be similar, maybe I should create Tesla.Shared module or something like that and move some duplicated functions.
> stream support for ibrowse

- lib/tesla/middleware/core.ex
- test/tesla/adapter/test_case.ex
https://github.com/myfreeweb/httpotion/issues/65
Sorry for the messy history.. only 1 line was actually changed. Unicode responses were not getting decoded properly and this seems to fix it.
> Add unicode support 

- README.md
- lib/tesla/middleware/tuples.ex
- test/tesla/middleware/tuples_test.exs
> Introduce Tesla.Middleware.Tuples

- lib/tesla/middleware/logger.ex
- test/tesla/middleware/logger_test.exs
I've noticed that I reimplement error logging in every next project, so I thought that perhaps it should be a core functionality. I believe having connection errors logged is as crucial as logging all "normal" responses.
> Log connection errors in Logger and DebugLogger middlewares

- lib/tesla.ex
- test/support/docs.ex
- test/tesla_test.exs
> Fixed doctests

- lib/tesla/middleware/tuples.ex
- test/tesla/middleware/tuples_test.exs
Closes #96 
@amatalai @Zeeker wdyt?
> Allow to pass additional errors to Tuples middleware

- lib/tesla.ex
- test/tesla_test.exs
> Add guards for options parameter

- lib/tesla/middleware/logger.ex
- test/tesla/middleware/logger_test.exs
> Add log_level option to Logger middleware

- lib/tesla/middleware/logger.ex
> Fix a documentation typo

- lib/tesla/multipart.ex
- test/tesla/multipart_test.exs
I thought i'd tackle this one since https://github.com/teamon/tesla/pull/231/ may or may not be abandoned.
Fixes #230
> Raise ArgumentError if multipart field is invalid.

- lib/tesla/middleware/telemetry.ex
- mix.lock
- test/tesla/middleware/telemetry_test.exs
This is the proper fix on pull request #289.
> Update telemetry to 0.4.0 and change the API for telemetry

- lib/tesla/middleware/retry.ex
- test/tesla/middleware/retry_test.exs
> Retry middleware support custom determination function

- .travis.yml
as discussed in https://github.com/teamon/tesla/pull/303#issuecomment-505116565
> Set dist in travis.yml to trusty for otp-18

- lib/tesla/adapter/gun.ex
- test/tesla/adapter/gun_test.exs
Added possibility to get response body as stream and in chunks.
Also added possibility for reusing opened connection.
> Expanding functionality of the gun adapter

- README.md
- lib/tesla/adapter/gun.ex
- lib/tesla/adapter/shared.ex
- test/tesla/adapter/gun_test.exs
Expanding gun adapter:
- unnecessary sni removed
- added certificates verification
- added support for socks proxy
- bug fixes for veryfy_fun and closing conn
- updated docs
- errors namings
- some code refactor
> Gun adapter

- README.md
- config/config.exs
- lib/tesla/adapter/mint.ex
- test/tesla/adapter/mint_test.exs
- fixed request body streaming
- fixed SSL test
- added possibility for reusing connection, get body as stream/chunks
> Mint adapter

- lib/tesla.ex
> Add | nil to status type

- lib/tesla/adapter/gun.ex
- test/tesla/adapter/gun_test.exs
- checking original url in adapter code
- flush stream on max_body error
- removed duplicate test
- removed `original` option in tests
- set `tls` transport for all `https` requests
> Gun adapter improvements

- lib/tesla/middleware/follow_redirects.ex
- test/tesla/middleware/follow_redirects_test.exs
Replacement for https://github.com/teamon/tesla/pull/361, solving https://github.com/teamon/tesla/issues/362.
@lizziepaquette , @chulkilee Mind taking a look?
> Keep authorization headers only if hostname is the same

- lib/tesla/middleware/telemetry.ex
Resolves #380.
Thanks for catching this @3duardo!
> Report microseconds in legacy telemetry event

- lib/tesla/adapter/gun.ex
- lib/tesla/adapter/mint.ex
> idna dep in gun docs

- lib/tesla/middleware/telemetry.ex
- test/tesla/middleware/telemetry_test.exs
A replacement for https://github.com/teamon/tesla/pull/390
> Add :metadata option to Telemetry middleware

- lib/tesla.ex
- test/tesla_test.exs
* Small improvements for the module `Tesla` options description
* Add example on how to use `:except` options
* Add example on how to use build_url with Keyword list. 
* Add tests for `build_url/2`
> Improve Tesla docs

- lib/tesla.ex
- lib/tesla/client.ex
> Fix typespec of adapter

- mix.exs
> Support telemetry v1.0

- .github/workflows/release.yml
See https://github.com/erlef/setup-beam/issues/20
> Migrate GitHub Actions to erlef/setup-beam

- mix.exs
> Add `castore` 1.0

- lib/tesla/middleware/opts.ex
- test/tesla/middleware/opts_test.exs
> fix: merging adapter options using Opts middleware

- lib/tesla/middleware/telemetry.ex
Reverts elixir-tesla/tesla#622
> Revert "feat: allow to configure the prefix for the telemtry events"

- README.md
- mix.exs
> fix: bump elixir version compatibility

- lib/tesla/adapter/httpc.ex
- mix.exs
- test/tesla/adapter/httpc_test.exs
Reverts elixir-tesla/tesla#626
> Revert "feat: add ssl opt to httpc by default"

- guides/howtos/migrations/v1-macro-migration.md
- mix.exs
> chore: add v1 macro migration guide

- mix.exs
List of changes:
- add changelog link to module info page
- add title to license page
- link changelog to releases page
> docs: docs housekeeping

- config/config.exs
- lib/tesla/builder.ex
related to #612
Signed-off-by: Yordis Prieto <yordis.prieto@gmail.com>
> chore: add warning message to Tesla.Builder
