elixir-tesla/tesla

.gitignore, lib/tesla.ex, lib/tesla/adapter/ibrowse.ex, lib/tesla/middleware/json.ex, mix.exs, mix.lock
* Add mix.lock to git
* Set deps environment groups inline
* Make `ibrowse` optional
* Use an empty list as default option for `with` macro
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/monterail/tesla/3)
=> Mix Dependency Improvements

lib/tesla/adapter/ibrowse.ex
Bodies were being ignored! This fixes that by passing the body down to ibrowse if present.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/monterail/tesla/7)
=> Use request body

lib/tesla/adapter/ibrowse.ex
lib/tesla/adapter/ibrowse.ex:48: warning: the underscored variable
"_body" is used after being set. A leading underscore indicates that
the value of the variable should be ignored. If this is intended please
rename the variable to remove the underscore
lib/tesla/adapter/ibrowse.ex:51: warning: the underscored variable
"_body" is used after being set. A leading underscore indicates that
the value of the variable should be ignored. If this is intended please
rename the variable to remove the underscore
lib/tesla/adapter/ibrowse.ex:52: warning: the underscored variable
"_body" is used after being set. A leading underscore indicates that
the value of the variable should be ignored. If this is intended please
rename the variable to remove the underscore
lib/tesla/adapter/ibrowse.ex:57: …
=> remove compile warning and don't create :ok tuple everytime

README.md, lib/tesla/middleware/core.ex, test/tesla/middleware/core_test.exs
First off, I'm excited to see an elixir HTTP library building on the concepts from Faraday. Plug and rack middleware are a powerful concept. Thank you for writing this library.
This PR adds a middleware for including default query params. Does the heavy
lifting of URI manipulation with URI module.
This middleware is helpful because certain APIs require access_tokens in
their query_params and it's helpful to set these as default using a
middlware.
```
defmodule Github.Api do
use Tesla.Builder
plug Tesla.Middleware.BaseUrl, "https://api.github.com"
plug Tesla.Middleware.Headers, %{'User-Agent' => 'elixir'}
plug Tesla.Middleware.QueryParams, %{access_token: "XXXXXXXXXXXXXXXXXXXXXXX"}
plug Tesla.Middleware.DecodeJson
adapter Tesla.Adapter.Ibrowse
end
```
=> Add QueryParams middleware

README.md
The 0.1.0 broke with recent Elixir versions
=> Update example dependencies

README.md
Parsing labels to atoms is a bad practise as it can lead to attacks overflowing the atom table and filling the memory with garbage. I switched the example to a different parser option that is safe to use.
=> Change JSX sample

lib/tesla/middleware/json.ex, test/tesla/middleware/json_test.exs
When using `Tesla.Middleware.EncodeJson` or `Tesla.Middleware.DecodeJson` without any options, like:
```elixir
defmodule EncodeDecodeJsonClient do
use Tesla
plug Tesla.Middleware.DecodeJson
plug Tesla.Middleware.EncodeJson
end
```
..one gets a `FunctionClauseError` when it tries to resolve what JSON engine to use:
```
JsonTest
...
* test EncodeJson / DecodeJson works without options (3.2ms)
1) test EncodeJson / DecodeJson works without options (JsonTest)
test/tesla/middleware/json_test.exs:88
** (FunctionClauseError) no function clause matching in Keyword.get/3
stacktrace:
(elixir) lib/keyword.ex:150: Keyword.get(nil, :engine, Poison)
(tesla) lib/tesla/middleware/json.ex:79: Tesla.Middleware.JSON.do_process/3
(tesla) lib/tesla/middleware/json.ex:68: Tesla.Middleware.JSON.process/3 …
```
=> Handle mission options for EncodeJson / DecodeJson

README.md, lib/tesla.ex, test/tesla_test.exs
Hello,
I added some configuration options for `use Tesla` and `use Tesla.Builder`
- :only and :except - limit generated functions
```
#usage
use Tesla, only: [:get, :post]
use Tesla, only: ~w(delete)a
use Tesla, except: [:get, :post]
use Tesla, except: ~w(delete)a
```
- :docs - disable generating docs, useful when you create package based on Tesla, but don't want docs for it contains docs for all get, post, put etc. functions generated by Tesla
```
defmodule MyProject.Module do
use Tesla, docs: false
@doc "custom function"
def custom_function: get("something")
end
```
=> Builder options

lib/tesla/middleware/follow_redirects.ex
Elixir was complaining about `env` and `next` being unused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teamon/tesla/54)
=> Fix warnings in FollowRedirects middleware

lib/tesla/middleware/follow_redirects.ex, test/tesla/middleware/follow_redirects_test.exs
Previously `redirect(env, next, 0)` raised error immediately when if fact I would expect it to check this last location and raise only if it return another redirect
=> Follow redirects improvement

lib/tesla/adapter/ibrowse.ex
It looks like this is already possible when using the `hackney` or `httpc` adapter, but not for `ibrowse`.
=> Pass options from env to ibrowse adapter

lib/tesla/middleware/basic_auth.ex, test/tesla/middleware/basic_auth_test.exs
Allow the generation Basic Authentication headers.
There was a request for this functionality on the Elixir Slack and it seemed like a fairly easy addition!
I've mostly just adapted the Digest Auth middleware and simplified it a bit.
Let me know if you'd like any modifications!
=> Add Basic Auth middleware

lib/tesla/middleware/logger.ex
`:timer.tc/2` returns elapsed time in *microseconds* and this value should be
divided by 1000 to get time in *milliseconds*.
See http://erlang.org/doc/man/timer.html#tc-2
=> Fix calculation of request-response cycle duration in Logger middleware

README.md
Since `mix.exs` has 1.3 version of elixir, it's worth adding this information. It will surely clarify things for the beginners.
=> Add info about adding tesla to the applications

README.md
Just getting started with Tesla today and was bitten by this because I was trying to use the BasicAuth middleware, but had copy-pasted my mix deps from the README.
=> Update mix deps examples in README for 0.7.0

lib/tesla/middleware/logger.ex, test/tesla/middleware/logger_test.exs
I found in my testing that it would be helpful to include logging in the DebugLogger of the params
=> This adds in logging for parameters

mix.exs
Adds the `:ssl` application to the list of applications in `mix.exs`.
When using the default `httpc` adapter, attempting to GET an https URL would result in the error `** (Tesla.Error) adapter error: :econnrefused`.
The `:econnrefused` error is actually hiding the root cause, which is `:ssl_not_started`.
It appears that the httpc adapter is not automatically starting the `:ssl` application.
I tried to find a way to make a test fail, but was unable to.  I believe that something else that loads during the test run starts the `:ssl` application, causing all of the tests to pass.
I did run this version with my application and it now works as I expect.
Fixes #74
=> Start the :ssl application

lib/tesla/middleware/follow_redirects.ex, test/tesla/middleware/follow_redirects_test.exs
The URL wasn't parsed correctly causing a relative path that starts with a "/" to be appended to the entire URL. 
The following URL `http://foo.com/hello` generates the following header `Location: "/world"`, appending "/world" to the entire URL creating `http://foo.com/hello/world`. It should be `http://foo.com/word`.
=> Fix absolute URL redirects

README.md, lib/tesla/adapter/hackney.ex, lib/tesla/adapter/httpc.ex, lib/tesla/adapter/ibrowse.ex, lib/tesla/middleware/form_urlencoded.ex, lib/tesla/middleware/json.ex, lib/tesla/multipart.ex, test/tesla/adapter/test_case.ex, test/tesla/middleware/form_urlencoded_test.exs, test/tesla/middleware/json_test.exs, test/tesla/multipart_test.exs, test/tesla/multipart_test_file.sh
I needed multipart support so I took a stab at it. Feedback welcome.
=> Add support for multipart requests.

.gitignore, lib/tesla/adapter/hackney.ex, test/tesla/adapter/hackney_test.exs
=> fix for hackney with_body option

lib/tesla.ex, test/tesla_test.exs
This change is backward compatible:
- Tesla.build_client API stays the same
- one can still use simple function as a client
Tesla.Client struct can hold any custom `fun` (as before)
but can now hold `pre` and `post` middleware lists.
`pre` works the same way as one given to `build_client`.
`post` middleware is injected right before adapter.
It can be used as a regular middleware but can be also
used to dynamically override adapter in runtime.
This is mostly useful in testing:
```ex
defmodule MyAPI do
use Tesla
def help(client \\ %Tesla.Client{}) do
get(client, "/help")
end
end
client = Tesla.build_adapter fn env ->
%{env | status: 200, body: "new body"}
end
assert %{body: "new body"} = MyAPI.get(client)
```
=> Introduce Tesla.Client with pre/post middleware

.gitignore, README.md, lib/tesla.ex, lib/tesla/mock.ex, test/tesla/mock_test.exs, test/tesla_test.exs
@amatalai, @hodak please take a look if you have a minute and let me know what do you think.
While this is working, I'm not sure how to handle adapter configuration:
- The default behaviour is to check client, then module (`adapter :hackney` in client module), then `config :tesla, :adapter` and then fallback to `Tesla.default_adapter`
- In test, it would be useful to override all setting and force mock adapter.
=> Introducing Tesla.Mock

README.md, lib/tesla/middleware/timeout.ex, test/tesla/middleware/timeout_test.exs
As proposed here: https://github.com/globocom/tesla_timeout/issues/3
If you have any improvements to ask, please tell us, so we can do it and merge.
=> Merging Globo.com Timeout middle for Tesla

README.md, lib/tesla/multipart.ex
Extend Multipart module with `add_file_content` function.
This allow us to pass a file content data, compared to `Multipart.add_file` where you must have a file on the FS.
Tipical use case: the file content data is retrieved from an external source (ex: DB, cache, ..) or is just in memory.
=> Add Multipart.add_file_content function

README.md
This bit me when I was trying to add tests, was scratching my head on why Tesla.Mock was not found.
=> Add warning that the shown README is not for the released version but for master

lib/tesla/middleware/timeout.ex
Killing the caller because of a timeout is not what people want to do.
=> Don't kill parent process when timeout occurs

README.md, config/config.exs, lib/tesla/mock.ex, test/support/mock_client.ex, test/tesla/global_mock_test.exs, test/tesla/mock/global_a_test.exs, test/tesla/mock/global_b_test.exs, test/tesla/mock/local_a_test.exs, test/tesla/mock/local_b_test.exs, test/tesla/mock_test.exs
Continuation of #136, also related to #140
I've moved setting up global mock into separate function to be explicit about it. It will also fail fast when used inappropriately with async test cases.
@Zorbash, @amatalai please take a look.
@gottfrois, @pawelduda, @Daniel-Xu please try using tesla from `global-mock` branch and let us know if there are any issues.
```elixir
{:tesla, github: "teamon/tesla", branch: "global-mock"}
```
=> Global mock support

test/tesla/mock_test.exs
I think this is more specific (and clear) given that `MockClient` plugs in `Tesla.Middleware.JSON`.
=> Improve Tesla.Mock test with JSON middleware

.formatter.exs
Enable importing the formatter config of tesla to the upstream users.
https://hexdocs.pm/mix/Mix.Tasks.Format.html#module-importing-dependencies-configuration
=> Export macro formatting in .formatter.exs

lib/tesla/middleware/compression.ex
=> Fix documentation typo's

lib/tesla/multipart.ex
Hey guys, I'm currently running `mix dialyzer` on your project to ensure everything is valid for usage. I've found some issues and, to make make sure they all go in nicely, having separate PRs for them.
This is the first one which is an unknown type. Mainly because the `Part` was never aliased in. Would this project prefer this structure, or `alias Tesla.Multipart.Part`? I would recommend taking the `Tesla.Multipart.Part` module and putting it in its own file. This would be more conventional and allow developers to find the module easier.
=> fix unknown type Part.t

lib/tesla/adapter/httpc.ex
Offense:
```erlang
lib/tesla/adapter/httpc.ex:51: The call 'Elixir.Keyword':pop_first(Vheaders@3::[any()],"Content-Type",[47 | 97 | 101 | 105 | 108 | 110 | 112 | 116 | 120,...]) breaks the contract (t(),key(),value()) -> {value(),t()}
```
So, it turns out that the Keyword module should _only_ take atoms as keys. Yeah, I know, it's silly. Except, the definition of a keyword list to elixir is where the keys are atoms and the values are any. Reference: https://hexdocs.pm/elixir/Keyword.html#t:key/0
Anywho, since the offender isn't actually a keyword list, but just a standard list, opting for a function that doesn't break the contract with Keyword is preferred. That's when I remade the behavior of `Keyword.pop_first/3` as a private function `list_pop_first/3`.
How it works: Looks up the …
=> fix broken contract with Keyword keys

lib/tesla/middleware/logger.ex
Just a drive by fix. I accidentally noticed the typo while reading the code.
=> Fix a typo in documentation

README.md
I noticed Firefox (at the the Developer Edition) shows a scary looking "connection is not secure" message because this asset is being requested over http:
And it still works over https: ![SEE!](https://inch-ci.org/github/teamon/tesla.svg) https://inch-ci.org/github/teamon/tesla.svg
=> Prefer https for docs coverage svg link (InchCI)

lib/tesla/builder.ex
Seems self explanatory. 😸 
In my project, I don't want the `request!` method to be included in my package's docs.
Happy to version-bump this if you require.
=> Add conditional @doc to request! method

lib/tesla/middleware/follow_redirects.ex, test/tesla/middleware/follow_redirects_test.exs
The current `Tesla.Middleware.FollowRedirects` simply updates the url of the response env and tries again. This means that the body from the previous response along with the headers are sent in the next request which can cause unpredictable results.
This PR preserves the original request for each redirect so the body (and optionally headers) can be used in the next request. 
Additionally
- added support for 303 redirects
- add the option to rewrite the method to `:get` on 301 and 302 responses
- optionally prevent or allow redirecting on 301 and 302 responses if the original request was other than `:get` or `:head`
I haven't written tests for all the cases yet, but if it looks good, please let me know and I'd be happy to write them (and fix any bugs I find while doing so)
=> [WIP] Update the redirect middleware to preserve the original request

lib/tesla/middleware/json.ex, test/tesla/middleware/json_test.exs
added `encode_content_type` option following the same pattern as `decode_content_types` 
Related Issue https://github.com/teamon/tesla/issues/212
=> Json middleware custom content type

lib/tesla/adapter/hackney.ex
Update documentation to fit the latest stable version.
+ change specified `hackney` version to latest one currently available in hex;
+ update adapter definition to support the newest module version as atoms are no longer supported;
=> Change hackney version in docs. Replace atom with full module definition

lib/tesla/adapter/ibrowse.ex
Allow passing a :timeout option to the ibrowse adapter, otherwise it will always use its hardcoded 30 second limit.
Example:
```
client =Tesla.build_client()
get(client, "/something", opts: [adapter: [timeout: 120_000]])
```
=> Expose the timeout parameter in ibrowse

README.md, lib/tesla.ex, lib/tesla/builder.ex, lib/tesla/middleware/basic_auth.ex, lib/tesla/middleware/digest_auth.ex, lib/tesla/migration.ex, test/tesla/middleware/basic_auth_test.exs, test/tesla/middleware/digest_auth_test.exs, test/tesla_test.exs
This is first part of #240
- Introduced `Tesla.client/1` & `Tesla.client/2` to configure client in runtime
- Deprecate `Tesla.build_client` & `Tesla.build_adapter`
=> Introduce Tesla.client/1 & Tesla.client/2

lib/tesla/middleware/form_urlencoded.ex, test/tesla/middleware/form_urlencoded_test.exs
Somehow the `Tesla.Middleware.FormUrlencoded` middleware is missing the decoding part 🐌
=> Decode application/x-www-form-urlencoded responses

lib/tesla/multipart.ex
Dialyzer output without this change:
```
lib/tesla/multipart.ex:130:invalid_contract
Invalid type specification for function.
Function:
Tesla.Multipart.body/1
Success typing:
@spec body(%Tesla.Multipart{:boundary => _, :parts => _, _ => _}) ::
(_, _ -> {:halted, _} | {:suspended, _, (_ -> any())})
________________________________________________________________________________
lib/tesla/multipart.ex:137:invalid_contract
Invalid type specification for function.
Function:
Tesla.Multipart.part_as_stream/2
Success typing:
@spec part_as_stream(%Tesla.Multipart.Part{:body => _, :dispositions => [{_, _}], :headers => _, _ => _}, _) ::
(_, _ -> {:halted, _} | {:suspended, _, (_ -> any())})
________________________________________________________________________________
```
The return type of …
=> Fix dialyzer warning for Multipart.part_stream type

lib/tesla/multipart.ex, test/tesla/multipart_test.exs
This fixes a bug I introduced in #251 where
vanilla streams now raise an ArgumentError
=> Allow vanilla Stream

lib/tesla/middleware/logger.ex, test/tesla/middleware/logger_test.exs
Basically the same as Phoenix' `config :phoenix, :filter_parameters, ["password", "secret"]` but for Tesla debug logs and headers.
```elixir
plug Tesla.Middleware.Logger, filter_headers: ["authorization"]
```
While you generally don't want to enable debug logs in production, it can be useful to do so once in a while.
=> Filter sensitive headers in debug logs with :sanitize_headers

lib/tesla/middleware/core.ex, test/tesla/middleware/base_url_test.exs
Replace #267
- Update doc and test for base url with path
- Previously, when empty url is given, the result url would have always `/` at the end. Now this behavior is changed to keep the original url (as in the base url middleware) as-is.
- Allow different case for http(s).
- No change for type (`url` is still expected be a string)
- I thought of using `URI.parse/1`, but just leave the current behaviour (passing only http(s))
```elixir
defp apply_base(%{url: url} = env, base) do
case URI.parse(url) do
%{scheme: nil} -> %{env | url: join(base, url)}
_ -> env
end
end
```
=> Base url improve: case-insensitive scheme and keep empty path

README.md
This example of setting the middleware for an api client throws the following compile errors
```
** (CompileError) lib/integration_tester/aversion_client.ex:7:
Adapter aliases and local functions has been removed.
Use full adapter name or define a middleware module Hackney
adapter :hackney
See https://github.com/teamon/tesla/wiki/0.x-to-1.0-Migration-Guide#dropped-aliases-support-159
```
The updated example compiles correctly.
=> Updated deprecated adapter example

README.md
Setting `ssl` has no effect, the option in hackney is called `ssl_options`
=> Use correct SSL options for Hackney

mix.exs
I have just realized I didn't add the middleware module onto the mix.exs.
So, just have a pr on this.
=> Adding telemetry docs to mix.exs

lib/tesla/adapter/hackney.ex, test/tesla/adapter/hackney_test.exs
The Hackney handler was not handling the async option correctly. The problem is
that Hackney would return `{:ok, ref}` as an asynchronous response and the
caller is expected to process messages using that reference.
The Hackney adapter did not have a handler for the `{:ok, ref}`. I added a
handler for the `{:ok, ref}` response that waits for the header and status
messages from Hackney, but passes back the `ref` as the body of the response.
The reason is that some async requests are long-living and require the end user
to implement the streaming data, i.e. mjpg. The header and the status should not
take much time and are expected in many instances.
No changes were needed in the DigestAuth module since DigestAuth doesn't use the
body.
I was able to use this on an mjpg async call and use a …
=> Allows DigestAuth to work with Hackney using the async option

lib/tesla/middleware/retry.ex
Hey! Thanks for this great library. We've been converting a lot of our http clients to Tesla and have been really happy with it so far.
One of the things that we found ourself needing was a retry middleware that did exponential backoff with jitter. I thought I would submit what we're using as a PR to see if its interesting to y'all. I wasn't sure if I should leave the existing retry middleware as is or if I should create a new `RetryWithBackoff` middleware. I opted to go this route because it seems like in most use cases you're going to want some sort of backoff and jitter as opposed to a set delay. That said this is probably a breaking change for _someone_ because they're probably relying on the existing algorithm.
Let me know what you think. Thanks again for all of the work on Tesla …
=> Add exponential backoff to retry middleware

README.md, lib/tesla/adapter/hackney.ex, lib/tesla/middleware/path_params.ex, test/tesla/middleware/path_params_test.exs
Implementation of #249 
TODO:
cc @jcabotc
=> PathParams middleware

lib/tesla/middleware/follow_redirects.ex, test/tesla/middleware/follow_redirects_test.exs
Redirects can be relative to the current URL.
e.g.
```elixir
iex(sr2@test)3> Tesla.get("https://webmention.rocks/test/23/page")
{:ok,
%Tesla.Env{
headers: [
{"location", "page/wjj46SaVj1OnFIzTBDwA"}, # …
],
status: 302,
}}
```
so it's the `^https?://` case where we can bypass URI parsing. In other cases, let `URI.merge` do its thing.
=> Fix relative redirect support

lib/tesla/adapter/mint.ex
Fix for `warning: function Mint.HTTP.stream/2 is undefined (module Mint.HTTP is not available)` which occurs in project where is used another adapter.
=> Fix for warning

lib/tesla/middleware/telemetry.ex
Fixes the warning about `:telemetry` not being in the app
=> Fix telemetry warning

README.md
Silly mistake on my part, but I blindly copied the `deps` example and spent a few minutes debugging why the Mint adapter wasn't working. Updating the README example for future blind copiers :)
=> Update Hex version in README

lib/tesla/adapter/gun.ex
Added clauses for error handling in opening connections with SOCKS and common usage.
Fixes #335.
=> Gun opening connection error handling

README.md
https://api.github.com/user/username/repos is a 404
=> I think there is a typo in the README

mix.exs
I added `source_ref` config incorrectly next to `source_url`. It should be nested inside `docs` section.
=> Move source_ref ex_doc config to docs section

lib/tesla/multipart.ex
I'm am running a worker which is trying to move over a fair bit of data from one location to a second one. This consists of a large number of small files. Tesla is somewhere in the dependencies, and I discovered that more than 50% of my cpu time is right now being spent generating random numbers for multipart. I created faster version to do more-or-less the same, and as for this script:
```
defmodule PerformanceTest do
@boundary_chars "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
|> String.split("")
def unique_string(length) do
Enum.reduce(1..length, [], fn _i, acc ->
[Enum.random(@boundary_chars) | acc]
end)
|> Enum.join("")
end
def fast_unique_string do
16
|> :crypto.strong_rand_bytes()
|> Base.encode16(case: :lower)
end
end
defmodule ProfilingExamples do
import …
```
=> improve random string performance

README.md
Due to unannounced breaking change in the OTP version 22.1 hackney below the version 1.15.2 stopped working.
Older versions are throwing `{:option, :server_only, :honor_cipher_order}` on OTP >= 22.1 and 1.15.2 fixes this issue.
Reference:
https://github.com/benoitc/hackney/issues/591
https://github.com/edgurgel/httpoison/issues/393
=> Bump recommended hackney to ~> 1.15.2

lib/tesla/multipart.ex
@boundary_chars is no longer used
=> Removed unused code

lib/tesla/middleware/timeout.ex, test/tesla/middleware/timeout_test.exs
Otherwise the stacktrace points to;
```
(tesla) lib/tesla/middleware/timeout.ex:54: Tesla.Middleware.Timeout.repass_error/1
(tesla) lib/tesla/middleware/timeout.ex:32: Tesla.Middleware.Timeout.call/3
(...)
```
which isn't very helpful.
=> When requests fails (while using timeout addition), preserve original stacktrace

lib/tesla/middleware/timeout.ex
Hi there,
first of all thanks for Tesla it's been making my life a lot easier through the included Mock and common things like Timeout and retry :)
Just a small doc fix to refer to the time unit actually used :)
Cheers,
Tobi
=> Refer correctly to the timeout unit used

lib/tesla/middleware/path_params.ex, test/tesla/middleware/path_params_test.exs
When `PathParams` middleware replaces the path params, it fails if the url contains the host with port (http://localhost: 7473/my_path/:whatever)
```elixir
** (ArgumentError) argument error
:erlang.binary_to_existing_atom("7473", :utf8)
(stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
(stdlib) erl_eval.erl:888: :erl_eval.expr_list/6
(stdlib) erl_eval.erl:411: :erl_eval.expr/5
(stdlib) erl_eval.erl:273: :erl_eval.expr/5
(elixir) lib/regex.ex:731: Regex.apply_list/5
(elixir) lib/regex.ex:726: Regex.apply_list/5
(elixir) lib/regex.ex:668: Regex.do_replace/4
```
It's unavoidable when using `BaseUrl`, `Telemetron.Instrumenter.Tesla` and `PathParams`. There is no order possible.
`Telemetron` needs `BaseUrl` to metric `host`, `PathParams` needs to be executed before `BaseUrl` because otherwise it …
=> Change regular expression in PathParms middleware to avoid replacing port in url

lib/tesla/middleware/fuse.ex, test/tesla/middleware/fuse_test.exs
Issue #351 
This `PR` also makes `Fuse` return the original response if the circuit is closed (fuse is not melted)
=> Improve Fuse with custom melt conditions

lib/tesla/adapter/gun.ex, test/tesla/adapter/gun_test.exs
After opening connection with certificates verification, if there are tls errors, gun adapter will wait for messages from `gun` until receive block timeout. With big timeout it can cause processes wait for message with connection which can't be opened at all. 
We explicitly call `:gun.await_up` to speed up getting error message.
=> Fix for timeout on tls errors in gun adapter

lib/tesla/adapter/mint.ex
I thought this might be helpful for someone else in the future. I spent some time looking for the default value for `timeout` in Hexdocs until I found it in the source code.
I've also mentioned that the value is in `milliseconds` to be more explicit.
Let me know what you think. Thanks!
=> Include `Tesla.Adapter.Mint` timeout's default value in documentation

lib/tesla.ex
It uses `Keyword.mege/2` on `opts` so it should be keyword, not a list with any value.
=> Fix typespec for opts

lib/tesla/adapter/hackney.ex
Now `:hackney.send_body/2` is wrapped with error handling
and will not crash with {:error, :closed} return (or any other than :ok)
This closes #314
=> add error handling to hackney adapter

lib/tesla.ex, lib/tesla/client.ex, test/tesla/client_test.exs
Created based on feedback to #369 
The `Tesla.Client` struct has a private legacy data structure intended to support macro-friendliness. This structure is different than the supported argument structure for `Tesla.client/2`. This means that one cannot copy the middleware or adapter from one client into a new one for example.
Since the internal structure is highly likely to change, we are keeping it private and adding accessor functions (`Tesla.Client.adapter/1` and `Tesla.Client.middleware/1`) for getting a client's adapter or middleware in a format compatible with `Tesla.client/2`.
This supports a workflow like:
```elixir
def my_client(gax_client)
middleware = Tesla.Client.middleware(gax_client)
adapter = Tesla.Client.adapter(gax_client)
Tesla.client(middleware, adapter)
end
```
=> Middleware and adapter functions

lib/tesla/middleware/decode_rels.ex, test/tesla/middleware/decode_rels_test.exs
This is the issue noticed in https://github.com/teamon/tesla/issues/286. It's also a real-world example held at https://webmention.rocks/
=> Add test example of unquoted rel.

lib/tesla/middleware/follow_redirects.ex, test/tesla/middleware/follow_redirects_test.exs
Implements https://github.com/teamon/tesla/issues/360#issuecomment-610344872
Merge after https://github.com/teamon/tesla/pull/371 is merged
=> Drop host header on redirect to a different hostname

lib/tesla/adapter/gun.ex, test/tesla/adapter/gun_test.exs
Changed:
- adapter would not open new connections on redirects, if passed `conn` option, because it doesn’t make sense if you use a connection pool and in some situations can lead to connections leaking. 
_For redirects handling with connection pool would be more correct to support redirects through custom `FollowRedirects` middleware, where you can properly open/close/checkin/checkout connections._
- little refactor
- some clean up in tests with removing duplicates
=> Simplifying gun adapter logic

lib/tesla/adapter/mint.ex
Adds consistency for opts passed to `receive_packet /3`.
[As mentioned here](https://github.com/teamon/tesla/pull/393/files#r440820751) `read_chunk/3` was calling `receive_packet/3` with opts as keyword.
=> moving opts into map for mint adapter

lib/tesla/adapter/gun.ex, lib/tesla/adapter/mint.ex, lib/tesla/middleware/telemetry.ex, lib/tesla/mock.ex, mix.exs
After struggling with a `Tesla.Mock.json/2` dialyzer warning at my application, I have found that the opts spec is a keyword list inside a list, instead of a plain keyword list.
So, I have analyzed other warnings and errors and also fixed those.
```
Checking PLT...
[:castore, :dialyxir, :elixir, :ex_doc, :exjsx, :fuse, :gun, :hackney, :ibrowse, :idna, :inets, :jason, :kernel, :logger, :mime, :mint, :mix_test_watch, :poison, :ssl, :ssl_verify_fun, :stdlib, :telemetry]
PLT is up to date!
No :ignore_warnings opt specified in mix.exs and default does not exist.
Starting Dialyzer
[
check_plt: false,
init_plt: '/Users/gabriel.medina/Git/tesla/_build/dev/dialyxir_erlang-22.3.4_elixir-1.10.3_deps-dev.plt',
files: ['/Users/gabriel.medina/Git/tesla/_build/dev/lib/tesla/ebin/Elixir.Tesla.Middleware.J …
```
=> Fix dyalizer errors and warns

lib/tesla/adapter/gun.ex
Adding `castore` dependency to gun docs as it is called in adapter code.
=> added castore dep in gun docs

lib/tesla/adapter/mint.ex
PR to fix issue https://github.com/teamon/tesla/issues/398
=> Makes mint adapter only accept mint messages during receive_message/2

lib/tesla/middleware/form_urlencoded.ex, test/tesla/middleware/form_urlencoded_test.exs
* Expose Tesla.Middleware.FormUrlencoded.encode/2 and Tesla.Middleware.FormUrlencoded.decode/2.
* Create 2 modules, Tesla.Middleware.EncodeFormUrlencoded and Tesla.Middleware.DecodeFormUrlencoded.
* Add tests.
Closes #410
=> Add DecodeFormUrlencoded and EncodeFormUrlencoded middleware

lib/tesla/middleware/retry.ex, test/tesla/middleware/retry_test.exs
When `delay` or `max_delay` are less than `1`, the Retry middleware currently crashes with the following error:
** (FunctionClauseError) no function clause matching in :rand.uniform_s/2
(stdlib 3.13) rand.erl:326: :rand.uniform_s/2
(stdlib 3.13) rand.erl:299: :rand.uniform/1
(tesla 1.3.3) lib/tesla/middleware/retry.ex:106: Tesla.Middleware.Retry.backoff/3
(tesla 1.3.3) lib/tesla/middleware/retry.ex:94: Tesla.Middleware.Retry.retry/3
It happens because `:rand.uniform/1` [requires](https://erlang.org/doc/man/rand.html#uniform-1) a positive integer.
~Make sure retry won't crash when either `delay` or `max_delay` are misconfigured.~
~This change adjusts `max_delay` to `1` when it isn't positive and also adjusts `delay` to make sure it falls within `1..max_delay`. Ideally, I believe we should …
=> Improve retry middleware option parsing

test/tesla/adapter/gun_test.exs, test/tesla/middleware/follow_redirects_test.exs, test/tesla/middleware/telemetry_test.exs
This PR fix warning complained by Elixir compile that variable tests is unused. The PR separate in 3 commits in 3 files.
=> Fix compile warning in tests

lib/tesla/middleware/follow_redirects.ex
Middlewares that come after FollowRedirects might use `opts` for state
they need to keep if they are called multiple times.
The specific use case we have that requires this: Our pool for
gun requires explicit checkout/checkin of the connection. We have a
middleware after FollowRedirects that checks out a connection, passes
it to adapter opts, requests and then checks the connection back in.
However, if `body_as: :chunks` options is used, we, obviously,
can't checkin the connection in the middleware as it needs to be passed
to the client after leaving the middleware. But if there was a redirect
to a different host we want to checkin the old connection and checkout
a new one ourselves. So we want to check if adapter options already
have a connection in them and checkin it if present.
=> FollowRedirects middleware: copy opts from response env

README.md
The badge shows the CI failing for tesla.
Ensure that the status been showed in the github actions badge is only for the master branch.
=> Show the Badge status for the master branch

README.md
hackney 1.15.x gives ssl errors with OTP-23
=> update hackney to 1.16 in readme

lib/tesla.ex, lib/tesla/middleware/logger.ex, test/tesla/middleware/logger_test.exs
This allows logger middleware to add a formatting
key for the query string. It is implemented by
piping `env.query` to inspect/1 for the sake of
simplicity.
To address #413
=> Add private output/4 for :query

README.md
`url` doesn't include query parameters.
=> Fix wrong output in README.md

mix.exs, test/test_helper.exs
And start optional dependencies in tests.
This fixes warnings on Elixir v1.11.
Closes #427.
Closes #429.
=> Let Elixir manage applications

lib/tesla/middleware/retry.ex, test/tesla/middleware/retry_test.exs
I noticed that the current backoff uses an uniformily distributed jitter. However, if the random distribution is trully uniform, this means that half of the time the backoff finishes at half the delay it would be expected to finish (e.g. at an attempt with delay 5000ms,  it has 50% probability to retry after 2500ms or less). This also introduces the problem that in some other percentage of the time the backoff is actually of linear or constant delay.
This PR refactors the function so the jitter is an additive noise proportional to the current delay, which should keep the backoff at the expected order of magnitude while adding the desired randomness.
A module option is provided to control said random noise level
=> feat: improve retry backoff jitter

lib/tesla/multipart.ex
I've fixed a type error on `Tesla.MultiPart.add_file/3`.
I've simply removed its option because there is no `:read` option for `File.stream!/3`.
If this patch has any problems. please let me know.
Thank you!
=> Fix type error

lib/tesla/builder.ex, test/tesla/builder_test.exs
Previously, in modules that `use Tesla, docs: false` the `option/0` type would
display in the generated documentation without any functions that refer to it in
the documentation.
=> Add documentation for `options/0` type and exclude when `docs: false`

lib/tesla/mock.ex
Problem:
Intermittent test failures when using `Tesla.Mock.mock_global/1` 
```elixir
** (exit) exited in: GenServer.call(#PID<0.16741.0>, {:update, #Function<2.71048325/1 in Tesla.Mock.agent_set/1>}, 5000)
** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
code: Tesla.Mock.mock_global(fn
stacktrace:
(elixir 1.10.4) lib/gen_server.ex:1023: GenServer.call/3
```
Current implementation:
`agent_set/1` is not atomic, and there's no guarantee pid returned by `Process.whereis/1` will be alive when making `Agent.update/2` call. That's because `Agent` process is linked to the test process, but the `exit(:shutdown)` signal is asynchronous, thus the same process can "leak" between test cases in …
=> Fix race condition of Tesla.Mock.mock_global/1

lib/tesla/middleware/digest_auth.ex
=> Use original HTTP method to retrieve digest authorization variables

lib/tesla/middleware/telemetry.ex, lib/tesla/middleware/timeout.ex, lib/tesla/mock.ex, test/tesla/middleware/timeout_test.exs
This PR replaces all deprecated `System.stacktrace()` calls with `__STACKTRACE__` ones removing these warnings from Elixir 1.11
=> Replace deprecated System.stacktrace() with __STACKTRACE__

lib/tesla/middleware/logger.ex
Hi, 
Currently, I am having an issue that I can't set the format of the logger at runtime because the current implementation takes the format string from the module attribute which is set at compile time. With this pull request, we will be able to set the format at run time with the below code sample.
```elixir
middleware = [
{Tesla.Middleware.Logger, format: "$method $url -> $status ($time ms)"}
]
client = Tesla.client(middleware)
```
=> Allow setting logger's format at runtime

lib/tesla/middleware/keep_request.ex, lib/tesla/middleware/telemetry.ex, test/tesla/middleware/keep_request_test.exs, test/tesla/middleware/telemetry_test.exs
This PR aims to provide a way for relaying through the `tesla.request.stop` event the unresolved path when using both Telemetry and PathParams middlewares.
The issue with the current implementation is that in success cases, it's impossible to retrieve the unresolved path from the event metadata
=> feat: add new event metadata to tesla telemetry

lib/tesla/adapter/finch.ex
Fixes typo in finch adapter docs
`checekd` --> `checked`
=> docs: fix typo in finch adapter docs

README.md, lib/tesla/middleware/bearer_auth.ex, mix.exs, test/tesla/middleware/bearer_auth_test.exs
Adds a `Tesla.Middleware.BearerAuth` middleware.
Basically, I had to use the bearer auth method, but Tesla doesn't have a middleware for it. So here is my small contribution :)
Wanted to include a wiki article on it in the module docs, but it's only listed as a part of Oauth...
=> Add BearerAuth middleware

lib/tesla/middleware/bearer_auth.ex
I noticed a small typo in the BearerAuth docs.
Additionally, I found that the documentation is not available on Hex.pm (https://hexdocs.pm/tesla/Tesla.Middleware.BearerAuth.html returns 404). Could the typo cause this? Anything else I can contribute to fix that?
Anyways, thanks for making my life easier with this awesome package 🙌  ❤️
=> Fix typo in BearerAuth docs

lib/tesla/middleware/telemetry.ex
Arity 3 does not exist here, the fourth argument is the handler config https://hexdocs.pm/telemetry/index.html that can be nil.
In the examples an anonymous function is passed in. For performance reasons these should be avoided. So perhaps that should be changed as well?
=> Use :telemetry.attach/4 in examples.

lib/tesla/mock.ex
I wasn't able to find how to do this in the documentation, but it's supported by the `call` function.  This PR adds an example to the `Setting up mocks` section of the docs.
I'm happy to rephrase things if "error tuple" is not the right term to use.
=> Document that Tesla.Mock can be configured to return error tuples

README.md
When playing around with configuring a timeout in the Hackney adapter, I discovered that you could specify options in `config.exs` but that option wasn't documented.  This PR adds that approach to the `README`.
=> Document that adapter options can be passed via config.exs

lib/tesla.ex, test/tesla_test.exs
Besides supporting nested keyword lists for query parameters, now a list of tuples where the first element of the tuple is binary is also supported.
This way there is no need to transform the list of tuples into a keyword, where the casting of keys into atoms could be dangerous when user input is used.
=> Support nested list of tuples in query parameters

mix.exs
The major change in `mime` is that there are less supported mime types: https://github.com/elixir-plug/mime/blob/master/CHANGELOG.md
I don't think that should be a problem for this library though.
=> Allow mime ~> 2.0

lib/tesla/middleware/fuse.ex
Under high load, forcing all calls to `:fuse.ask/2` to be synchronous (sent
through the `fuse_server` process) can result in a deep mailbox and timeouts
inside the middleware (hitting the default call timeout of 5s). This commit adds
a `mode` option to the middleware that lets the user select `:async_dirty` so
that the `fuse_server` process can be bypassed.
In the documentation, I tried to be explicit that choosing `:async_dirty` might
result in drift, meaning that a given process might read the fuse state from
`ets` and it would not account for melts or resets that are in the mailbox of
the `fuse_server` process.
Because of potential side-effect/timing issues, it wasn't clear how to test this
change. Any guidance there is appreciated!
=> Allow Tesla.Middleware.Fuse options to set the ask mode

lib/tesla/multipart.ex
added a return type because an error can occur by ":ok = assert_part_value!(value)" (71 line)
=> Add return type Multipart.add_field/4

lib/tesla/middleware/telemetry.ex, test/tesla/middleware/telemetry_test.exs
I think it would be useful to have `Tesla.Env.t()` in "tesla.request.exception" metadata unless the are objections against it.
=> Add Tesla.Env.t() to tesla.request.exception Telemetry metadata

lib/tesla/middleware/retry.ex
This PR is fairly straight-forward. The current implementation basically has no jitter (which isn't necessarily a serious bug, but is a bug still).
=> fix: jitter should user * instead of +

lib/tesla/middleware/telemetry.ex
Since Elixir `>= 1.14`, it checks for mixed/disallowed unicode characters, so using the micro sign in identifiers is no longer allowed.
=> Remove micro sign

lib/tesla/middleware/logger.ex, test/tesla/middleware/logger_test.exs
Sometimes we need a custom formatter to log the request body or something similar.
Heavily based on Elixir's Logger.Formatter
=> Allow set custom formatter for logger

README.md
Looking at the code I found the middleware but was also confused why it existed. The decode was documented, not the encode. so clearing the confusion
=> Update missing encodeJson middleware in Readme

lib/tesla/middleware/compression.ex, test/tesla/middleware/compression_test.exs
Avoid having to add an extra header when using the Compression or Compression derivatives middleware.
=> Compression Middleware: Add accept-encoding header when appropriate

README.md
I did not think it was clear to use `MyApp.get/1` since the function was not defined in a previous example.
=> Update testing example

lib/tesla.ex
The current [example code](https://hexdocs.pm/tesla/Tesla.Middleware.html#module-examples) in the Tesla.Middleware documentation will not work as it is. The `inspect_headers` function does not return the `env` arg, which is what `Tesla.run` expects as the first arg. This results in this confusing error:
```** (ArgumentError) you attempted to apply a function named :opts on []. If you are using Kernel.apply/3, make sure the module is an atom. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map```
In addition, the result of running the HTTP request will be an :ok/:error tuple, not the bare `Tesla.env` struct, so you need a different function (or different args) to handle that case.
Happy to tweak the approach here …
=> Update Tesla.Middleware documentation with functioning example code

config/config.exs, lib/tesla/adapter/httpc.ex, lib/tesla/builder.ex, lib/tesla/middleware/follow_redirects.ex, lib/tesla/middleware/method_override.ex, test/tesla/adapter/gun_test.exs, test/tesla/adapter/hackney_test.exs, test/tesla/adapter/httpc_test.exs, test/tesla/adapter/ibrowse_test.exs, test/tesla/adapter/mint_test.exs
Currently we are creating a request with body and content_type in many cases for methods that can't support it. Httpc doesn't know what to do an outputs a function match error.
=> fix httpc bodyless methods

lib/tesla.ex
The example was not being rendered correctly in the docs because it wasn't indented correctly.
=> Correctly indent code example

lib/tesla/adapter/mint.ex
While looking into an API that required using special options passed into `transport_opts`, I noticed that Mint supports it but that Tesla had no docs on whether `transport_opts` was a valid option for this adapter. Looking at the code, Tesla does support passing `transport_opts` into Mint. I think this would be a useful addition to the docs.
=> Adds docs to the Mint adapter on 'transport_opts'

lib/tesla/adapter/mint.ex, mix.exs, test/tesla/adapter/mint_test.exs
We encountered an in-the Mint adapter in Tesla. The error arises when we try to issue a new request but the connection was previously closed by the server. The response is a tuple of three elements, including the closed connection struct, but only two elements are expected in the behavior. In consequence, if we chain the Logger middleware this error happens: `FunctionClauseError: no function clause matching in Tesla.Middleware.Logger.log_level/2`
We can reproduce it by closing the connection before issuing the request, an example is:
Given this module
```elixir
defmodule A do
use Tesla
adapter Tesla.Adapter.Mint
plug Tesla.Middleware.Logger
def get(), do: get("http://localhost:5984/ping")
end
```
```elixir
iex(15)> A.get
** (FunctionClauseError) no function clause matching in …
```
=> Ensure connection errors return the expected error tuple

lib/tesla/middleware/logger.ex, lib/tesla/middleware/telemetry.ex, mix.exs
close #579 
Changes:
1. Replace Application.get_env with Application.compile_env in `Tesla.Middleware.Logger.Formatter` & `Tesla.Middleware.Telemetry` modules.
2. Put prefix with unused vars.
=> Replace get_env with compile_env in module body

lib/tesla/middleware.ex
I stumbled about this very case previously and had to read into the source code to clear up what was happening.
I understand that I'm somewhat paraphrasing what the actual implementation does (Decoration pattern), but I think for the documentation this is probably okay.
Let me know if the information provided here is sufficient.
=> Explained middleware ordering

README.md
Small fix to Readme link to the Plug Router
It's currently not jumping to the right place as expected as there is a slightly outdated link url. This PR fixes it.
=> Fixes README.md link to Plug Router

lib/tesla/middleware.ex, lib/tesla/middleware/retry.ex, test/tesla/middleware/retry_test.exs
Closes https://github.com/elixir-tesla/tesla/issues/578
I also formatted the middleware.ex as it caused the lining test to fail aaaand made a typo in the branch name 🤦
~I am open to ideas on how to make this work with what is described in that issue... I needed a way to prevent Retry from repeating POST/PUT requests on timeouts, so I wrote it and at first glance thought it was the same issue, but now I see it isn't :)~
Edit: with the addition of the suggested changes by @yordis, this now does in fact close the aforementioned issue 🎊
=> feat: add support for should_retry with arity of 2 to Retry middleware

lib/tesla/adapter/mint.ex, test/tesla/adapter/mint_test.exs
=> fix: use mint passive mode

lib/tesla/middleware/compression.ex, mix.exs, test/support/test_support.ex, test/tesla/middleware/compression_test.exs
We need to come up with some consensus about the feature!
closes #598
=> feat: improve decompression middleware

lib/tesla/middleware/telemetry.ex
Recently, @seancribbs asked to be able to control the prefix.
What is the proper solution here?
1. Allow people to customize the prefix
2. Hook into the events and, based on the data, do something with it, such as using the HOST information of the request or User-Agent
3. ?????
=> feat: allow to configure the prefix for the telemtry events

lib/tesla/middleware/logger.ex
Elixir 1.15 is now warning whenever the `:warn` level is used with the
recommendation of using `:warning` instead. The `Logger` middleware uses
`Logger.log/3`, so a compile-time warning would not be shown, only
a runtime warning.
This change adds `:warning` as a valid configuration option for Tesla
log level and automatically translates `:warn` or `:warning` to the
appropriate level (`:warn` for Elixir 1.10.x, `:warning` for Elixir
1.11.x or higher, as `Logger.warning/2` was introduced in 1.11.0).
=> Update Tesla.Middleware.Logger for Elixir 1.11+

lib/tesla/middleware/path_params.ex, test/tesla/middleware/path_params_test.exs
Tesla.Middleware.PathParams has been extended to support OpenAPI style parameters in addition to the existing Phoenix style parameters.
- Phoenix parameters begin with `:` and a letter (`a-zA-Z`) and continue to the next non-word character (not `a-zA-Z0-9_`). Examples include `:id`, `:post_id`, `:idPost`.
- OpenAPI parameters are contained in braces (`{}`), must begin with a letter (`a-zA-Z`) and may contain word characters and hyphens (`-a-zA-Z0-9_`). Examples inlucde `{id}`, `{post_id}`, `{IdPost}`.
Parameter value objects may be provided as maps with atom or string keys, keyword lists, or structs. During path resolution, to avoid potential atom exhaustion, the parameter value object is transformed to a string-keyed map.
Parameter values that are `nil` or that are not present in the …
=> feat: Middleware.PathParams: add OpenAPI params

lib/tesla/adapter/finch.ex, test/tesla/adapter/finch_test.exs
SSE introduced inconsistent error here: https://github.com/elixir-tesla/tesla/blob/tt/finch-stream/lib/tesla/adapter/finch.ex#L143
Finch adapter was always expecting Mint error.
I've looked at other adapters and seems like `{:error, :timeout}` is used consistently, previous error-handling implementation would respond with `{:error, "timeout"}` - thus the change not to use `Exception.message/1` anymore. This is potentially a breaking change for anyone using Finch adapter.
=> [Finch] Change error handling, fix for response stream

README.md, lib/tesla/adapter/finch.ex, lib/tesla/middleware/json.ex, lib/tesla/middleware/sse.ex, mix.exs, test/support/adapter_case/stream_request_body.ex, test/support/adapter_case/stream_response_body.ex, test/tesla/adapter/finch_test.exs, test/tesla/middleware/json_test.exs, test/tesla/middleware/sse_test.exs
- Request streaming support #506 
- First take on response streaming support #271
The implementation requires spawning a process, I'm not sure there's a way to implement streaming without it given `Finch.stream/5` only returns after all data has been streamed and the idea for tesla response streaming is to return `Tesla.Env` with status & headers and body as a stream.
```elixir
defmodule OpenAI do
def new(token) do
middleware = [
{Tesla.Middleware.BaseUrl, "https://api.openai.com/v1"},
{Tesla.Middleware.BearerAuth, token: token},
{Tesla.Middleware.JSON, decode_content_types: ["text/event-stream"]},
{Tesla.Middleware.SSE, only: :data}
]
Tesla.client(middleware, {Tesla.Adapter.Finch, name: MyFinch})
end
def completion(client, prompt) do
data = %{
model: "gpt-3.5-turbo",
messages: [
%{role: …
```
=> Request/Response streaming for Finch adapter, SSE middleware

README.md
- Also prefer the `~>` operator when installing packages (e.g. Jason)
- This is the format used in [the Jason documentation](https://github.com/michalmuskala/jason#installation)
- Pin to major versions instead of minor
=> Update README to use newest versions of dependencies

lib/tesla/adapter/finch.ex
This will bring a stream into memory, which can take a lot of memory unnecessarily
Admittedly there is a lot of intermediate code that I can't attach here, but replacing the finch adapter with the httpc adapter looks like this with a 10G multipart request body:
Finch adapter:
httpc adapter:
(Notice that the units are different between the two screenshots, one is in MB and the other in GB)
I can try to characterize the memory issue I am seeing with a test if you would like to see, but uploading a big file to see a memory spike in a test seems like a test you wouldn't want in the long term.
=> remove seemingly unnecessary step

lib/tesla/mock.ex
In some situations, the pid_holder is a registered process (e.g, MyApp.Supervisor). Process.info/1 does not support this, so we have to use Process.whereis/1 to resolve the actual pid.
This small issue was introduced between 1.9 and 1.10.
=> fix: Support registered names in mock

.github/workflows/release.yml, .github/workflows/test.yml, lib/tesla/adapter/hackney.ex, test/tesla/middleware/timeout_test.exs
> I am trying to maintain (in CI) the latest 2 major versions, so Elixir 15+ and OTP 25+; wait 2-3 months and it will be Elixir 16+ and OTP 26+
https://github.com/elixir-tesla/tesla/pull/623#issuecomment-2176886751
This approach runs fewer permutations, so we're not attempting an old version of Elixir on a new version of Erlang. We also can flag the latest version or release candidate as experimental, so that it doesn't block merging, but still reports the failures.
=> Update CI with current Elixir and Erlang/OTP versions

lib/tesla/middleware/json.ex, mix.exs, test/tesla/middleware/json_test.exs
=> fix: json decoder middleware for uppercase content type

lib/tesla/middleware/retry.ex, mix.exs, test/tesla/middleware/retry_test.exs
Related to https://github.com/open-telemetry/opentelemetry-erlang-contrib/pull/334
It will allow us to set `Trace.http_retry_count()` telemetry
=> feat: add retry_count opt in the retry middleware

lib/tesla/adapter/httpc.ex, mix.exs, test/tesla/adapter/httpc_test.exs
fixes #293
Signed-off-by: Yordis Prieto <yordis.prieto@gmail.com>
=> feat: add ssl opt to httpc by default

lib/tesla/adapter/httpc.ex
OpenSSL sets this to 100 by default, which prevents validation errors for endpoints presenting a longer certificate chain.
Reference:
* https://docs.openssl.org/3.3/man3/SSL_CTX_set_verify/#notes
=> TLS & httpc: suggested higher limit of max intermediate certs

lib/tesla.ex, lib/tesla/adapter/mint.ex, lib/tesla/builder.ex, lib/tesla/middleware/form_urlencoded.ex, lib/tesla/middleware/keep_request.ex, lib/tesla/middleware/telemetry.ex, lib/tesla/middleware/timeout.ex, lib/tesla/multipart.ex, test/tesla/middleware/digest_auth_test.exs, test/tesla/middleware/json_test.exs
=> Fix typos and improve language

lib/tesla/adapter/gun.ex, test/tesla/middleware/logger_test.exs
Found via `typos --hidden --format brief`
=> docs: fix typos again

lib/tesla.ex, test/tesla_test.exs
This ensures that the returned `Tesla.Env` includes the adapter used to make the call. This will help debug which adapter was used and also reflect what truly happened at runtime.
Before
```elixir
iex(1)> Tesla.get("https://httpbin.org/get")
{:ok,
%Tesla.Env{
__client__: %Tesla.Client{
adapter: nil
}
}}
```
After
```elixir
iex(1)> Tesla.get("https://httpbin.org/get")
{:ok,
%Tesla.Env{
__client__: %Tesla.Client{
adapter: {Tesla.Adapter.Httpc, :call, [[]]}
}
}}
```
=> fix: ensure adapter is set

guides/explanations/3.adapter.md, lib/tesla.ex, lib/tesla/adapter/finch.ex, lib/tesla/adapter/gun.ex, lib/tesla/adapter/hackney.ex, lib/tesla/adapter/httpc.ex, lib/tesla/adapter/ibrowse.ex, lib/tesla/adapter/mint.ex, lib/tesla/error.ex, lib/tesla/middleware/logger.ex, test/support/adapter_case/basic.ex, test/tesla/middleware/logger_test.exs, test/tesla/middleware/retry_test.exs, test/tesla_test.exs
I was adapting Tesla in a project when we encode query params with `:rfc3986` and I noticed that, while Tesla provides conveniences to build url encoding query params for us, it doesn't allow to specify the encoding strategy.
This PR allows specifying option `query_encoding: :rfc3986` so that whitespaces in query params will be encoded as "%20".
```elixir
Tesla.get("http://example.com", query: [username: "John Smith"], opts: [query_encoding: :rfc3986])
```
will build the following url
```
http://example.com?username=John%20Smith
```
Also adds optional argument to `Tesla.build_url` and `Tesla.encode_query`.
----
Tesla uses [URI.encode_query/2](https://hexdocs.pm/elixir/1.14.3/URI.html#encode_query/2) to encode query params. Since Elixir 1.12 that function allows to specify the encoding …
=> feat: allow to specify encoding strategy for query params

lib/tesla/mock.ex, test/tesla/mock_test.exs
`!is_nil(Process.get(ancestor, __MODULE__))` always returns true, hence the `find` fn returns the first ancestor. 
Iterate properly over ancestors trying to find the `__MODULE__` key.
cc/ @yordis
=> Fix. Mock not working for grandchildren and beyond

lib/tesla/adapter/hackney.ex
=> fix: add basic Hackney 1.22 support: {:connect_error, _}

lib/tesla/adapter/finch.ex
I found an error using Finch adapter in conjunction with streamed responses. The adapter doesn't take into account the `{:trailers, trailers}` command and raises an error.
=> fix: handle HTTP response trailers when use Finch + stream

lib/tesla/mock.ex
Hi!
I've run into an issue while running tests:
```
** (RuntimeError) failed to start child with the spec %{id: Tesla.Mock, start: {Agent, :start_link, [#Function<1.5545190/0 in Tesla.Mock.agent_set/1>, [name: Tesla.Mock]]}}.
Reason: bad child specification, got: {:already_started, #PID<0.8504.0>}
code: {:ok, activity} = create_successful_payment(%{"barcode" => tok.barcode}, acq, @payment_method)
stacktrace:
(ex_unit 1.18.2) lib/ex_unit/callbacks.ex:590: ExUnit.Callbacks.start_supervised!/2
(tesla 1.14.0) lib/tesla/mock.ex:152: Tesla.Mock.mock_global/1
```
Quick debugging session showed that it is a race condition in the `agent_set` function.
It performed:
```
case Process.whereis(__MODULE__) do
nil ->
ExUnit.Callbacks.start_supervised!(...)
```
My fix removes the check and tries to start …
=> Fix race condition in Tesla.Mock.agent_set

lib/tesla/mock.ex
The process `$ancestor` list can contain named processed as well as pids in certain supervision tree structures. This PR fixes a crash that happens with `Tesla.Mock` when a mocked module is called from within a spawned task within a named supervision tree, by looking up the pid of the named process if it exists.
Here is a trivial example showing the problematic `$ancestors` behaviour that causes the error
```elixir
iex(1)> Supervisor.start_link([{Task.Supervisor, name: MyTaskSup}], [name: MySup, strategy: :one_for_one])
{:ok, #PID<0.109.0>}
iex(2)> Task.Supervisor.async(MyTaskSup, fn -> :erlang.get(:"$ancestors") end) |> Task.await()
[#PID<0.110.0>, MySup, #PID<0.108.0>, #PID<0.98.0>]
```
=> fix: Handle named ancestors in Tesla.Mock

lib/tesla/adapter/finch.ex
The docs are missing one specific option for the Finch adapter: `:response`. It is mentioned in the [cheat sheet docs](https://hexdocs.pm/tesla/general.html#streaming-response-body) but not in the Finch Adapter.
=> docs: add Finch adapter specific stream option
